### ISSUE TITLE
Low data mode and mempool monitor

### ISSUE THREAD

**Issue by nachog00** [zingolabs/zingo-mobile#689] opened 2024-09-02 16:00 UTC
## Overview
> A user on cellular data sees a confirming transaction disappear until they connect to WiFi, where it reappears as fully confirmed, while the sender already saw confirmations.
## Steps to replicate
1. User **isn't connected to WiFi**, but to cellular data.
2. User gets a transaction sent to them.
3. User (receiver) sees the transaction as *confirming*
4. Sender sees confirmations already
5. Receiver doesn't see the transaction anymore, neither confirming nor confirmed.
6. Receiver connects to WiFi
7. Transaction shows up on receiver's end fully confirmed.

**Comment by juanky201271** [comment] 2024-09-02 16:11
Thanks @nachog00.
Are you able to reproduce in production or locally (dev branch)? do you have a video/s (sender/receiver) to document the issue?

**Comment by nachog00** [comment] 2024-09-04 22:51
This on the top list of things to emulate with AS.
Would you also benefit from a manual recreation and recording of the issue @juanky201271 ?

**Comment by juanky201271** [comment] 2024-09-09 15:26
Ey, @nachog00 I just realized that it could be good to test this behavior with this PR: https://github.com/zingolabs/zingo-mobile/pull/678 because here we split the `pending` status in two different states: `transmitted` & `mempool`.
I don't think the problem will be solved per se, but the App maybe will be more clear with the user about what is happening with the transaction...

**Comment by nachog00** [comment] 2024-09-14 15:10
That's a good idea.
Btw, should we move this issue into `zingolabs` repo? Since you mentioned it isn't really `zingo-mobile`  related

**Comment by juanky201271** [comment] 2024-09-14 15:26
That PR is merged already. You can test it from `dev` if you want to.

**Comment by juanky201271** [comment] 2024-09-22 16:04
@sebastianlujan or @nachog00  were you able to reproduce this issue locally in `dev`? any video or documentation?

**Comment by juanky201271** [comment] 2024-10-11 19:33
Personally I cannot reproduce this problem, no in my IPhone, no with Android Emulator, impossible. I followed the steps, but no luck. @Edicksonjga can you reproduces this in some device?

**Comment by Edicksonjga** [comment] 2024-10-11 20:26
I will try to do those tests, but not for previous tests, it looks like the bug reported before where transactions disappear when you put the app in the background and reopen, you have to wait for it to connect to the server to show up that last transaction made.

**Comment by juanky201271** [comment] 2024-11-25 18:07
Impossible to reproduce, I think this is not happening anymore.

**Closed as completed by juanky201271** 2024-11-25 18:07 UTC
Labels: bug, medium-priority, userfacing
