### ISSUE TITLE
Synking is Slow

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#198] opened 2023-02-16 21:46 UTC
Even though I entered this wallet a couple days ago, it hasn't synked to the present day.

zingo 119
android 11

sometimes it looks like this
sometimes it looks like this

![Screenshot_20230216-214436](https://user-images.githubusercontent.com/111296437/219494150-7f26a273-d7ac-47fc-993f-14d7a7ecaf40.png)
![Screenshot_20230216-214406](https://user-images.githubusercontent.com/111296437/219494151-16c8d3c0-13f9-42e5-8a97-8b82e751eb40.png)

**Comment by juanky201271** [comment] 2023-02-16 23:12
@fluidvanadium 

one observation is: With this amount of Battery, the BS is not working... (maybe you can change the setting about `battery optimization` for this App specifically???

The loading screen... What is the deal? please more info. When you go from background to foreground, the App have to restart the syncing with the server and sometimes this screen can block the UI... maybe mmmm, 10 seconds, but not more...

Here we can change this... and when the user do this back -> fore... restart the App, sending the focus to Loading App component... What do you think?

**Comment by juanky201271** [comment] 2023-03-08 21:20
@fluidvanadium 
Tell me if I can help you with something more about this issue...

**Comment by juanky201271** [comment] 2023-04-10 20:54
@fluidvanadium 
I'm going to ask for last time, before closing this issue...
Anything about this issue?

**Comment by juanky201271** [comment] 2023-05-13 16:07
The sync process could be slow, but the problem is not in the UI. closing...

**Closed as completed by juanky201271** 2023-05-13 16:07 UTC
Labels: userfacing
